# Generated by Django 4.2 on 2023-12-10 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='source_lang',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean')], default='English', max_length=30),
        ),
        migrations.AddField(
            model_name='video',
            name='target_lang',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Korean', 'Korean'), ('Urdu', 'Urdu')], default='Urdu', max_length=30),
        ),
        migrations.AlterField(
            model_name='translation',
            name='tv',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('response', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.chat')),
            ],
        ),
    ]
