# Generated by Django 5.0.2 on 2024-02-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_chat_video_source_lang_video_target_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='voice_type',
            field=models.CharField(choices=[('1', 'Male'), ('0', 'Female')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_lang',
            field=models.CharField(choices=[('english', 'english'), ('chinese', 'chinese'), ('urdu', 'urdu'), ('german', 'german'), ('spanish', 'spanish'), ('russian', 'russian'), ('korean', 'korean'), ('french', 'french'), ('japanses', 'japanses'), ('portugese', 'portugese'), ('turkish', 'turkish'), ('polish', 'polish'), ('dutch', 'dutch'), ('arabic', 'arabic'), ('swedish', 'swedish'), ('italian', 'italian'), ('indoesian', 'indoesian'), ('hindi', 'hindi'), ('finnish', 'finnish'), ('ukrainian', 'ukrainian'), ('romanian', 'romanian'), ('danish', 'danish'), ('hungarian', 'hungarian'), ('tamil', 'tamil'), ('norwegian', 'norwegian'), ('thai', 'thai'), ('persian', 'persian'), ('serbian', 'serbian')], default='english', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='target_lang',
            field=models.CharField(choices=[('english', 'english'), ('chinese', 'chinese'), ('urdu', 'urdu'), ('german', 'german'), ('spanish', 'spanish'), ('russian', 'russian'), ('korean', 'korean'), ('french', 'french'), ('japanses', 'japanses'), ('portugese', 'portugese'), ('turkish', 'turkish'), ('polish', 'polish'), ('dutch', 'dutch'), ('arabic', 'arabic'), ('swedish', 'swedish'), ('italian', 'italian'), ('indoesian', 'indoesian'), ('hindi', 'hindi'), ('finnish', 'finnish'), ('ukrainian', 'ukrainian'), ('romanian', 'romanian'), ('danish', 'danish'), ('hungarian', 'hungarian'), ('tamil', 'tamil'), ('norwegian', 'norwegian'), ('thai', 'thai'), ('persian', 'persian'), ('serbian', 'serbian')], default='urdu', max_length=30),
        ),
    ]
