# Generated by Django 5.0.2 on 2024-03-25 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_video_voice_type_alter_video_source_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='voice_type',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], default='1', max_length=30),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
